name: "Build"

on:
  push:
  pull_request:

jobs:
  nixos:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-nix
      - run: nix build .#nixosConfigurations.eagle.config.system.build.toplevel
