name: "Update flake"

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-nix
      - name: Update flake.lock
        run: nix flake update
      - name: Build NixOS configuration
        run: nix build .#nixosConfigurations.eagle.config.system.build.toplevel
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update flake.lock"
